In [11]:
# For Kmeans algorithm. See PGM otherwise for handcrafted class
from sklearn.cluster import KMeans
# For loading matlab matrix file
from scipy.io import loadmat
import numpy as np

In [12]:
import matplotlib.pyplot as plt
%matplotlib inline
%load_ext autoreload
%autoreload 2
%precision %.5f
plt.rc('text', usetex=True)
plt.rc('font',**{'family':'serif','serif':['Palatino']})

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [13]:
def SC(W, n):
    """
    Spectral Clustering algorithm.
    :param W: affinity matrix NxN (N : number of points)
    :param n: number of clusters
    :return : Segmentation of the data in n groups
    """
    # 1. Construct an affinity graph G with weight matrix W
    # 2. Compute the degree matrix D = diag(W1) and the Laplacian L = D - W
    D = np.diag(W.sum(axis = 1))
    L = D - W
    # 3. Compute the n eigenvectors of L associated with its n smallest eigenvalues
    ## May use scipy.sparse.linalg.eigs to speed up computation
    ## Use eigh if always symetric one > test the speed
    ## The vectors returned by linalg are normalized
    evalues, evectors = np.linalg.eig(L)
    # 4. Y : transpose of matrix of eigenvectors normalized by euclidien norm
    Y = evectors[:, -n:].T
    # 5. Cluster the points {y_j}_1^N into n groups using the K-means algorith

In [24]:
A = np.array([[1,-2], [6,4]])
A

array([[ 1, -2],
       [ 6,  4]])

In [25]:
np.linalg.eigh(A)

(array([-3.68465844,  8.68465844]), array([[-0.78820544,  0.61541221],
        [ 0.61541221,  0.78820544]]))

In [21]:
np.linalg.eigh(A)[1][:, -2:]

array([[-0.85065081,  0.52573111],
       [ 0.52573111,  0.85065081]])